In [25]:
import cv2
import numpy as np
import math

# Load the image
img = cv2.imread('img/Predictive_Modeling_Model_Performance_1.jpg')
# Prepocess


In [ ]:
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
cv2.imshow("out", gray)
cv2.waitKey(0)  

flag, thresh = cv2.threshold(gray, 200, 255, cv2.THRESH_BINARY)
cv2.imshow("out", thresh)
cv2.waitKey(0)  

adaptive_without_blur = cv2.adaptiveThreshold(gray, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY, 11, 3)
cv2.imshow("adaptive_without_blur", adaptive_without_blur)
cv2.waitKey(0)

img_blur = cv2.medianBlur(gray, 3)
adaptive_threshold = cv2.adaptiveThreshold(img_blur, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY, 11, 3)
cv2.imshow("adaptive_with_blur", adaptive_threshold)
cv2.waitKey(0)

kernel = np.ones((5,5),np.uint8)
erosion = cv2.erode(img,kernel,iterations = 10)

bilateral = cv2.bilateralFilter(gray, 5,40,40)
adaptive_threshold_bi = cv2.adaptiveThreshold(bilateral, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY, 11, 3)
cv2.imshow("adaptive_bilateral_filter", adaptive_threshold_bi)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [13]:

img_countours = img.copy()

contours, hierarchy = cv2.findContours(adaptive_threshold_bi, cv2.RETR_TREE, cv2.CHAIN_APPROX_NONE)
image_with_contours = cv2.drawContours(img_countours,contours, -1, (0, 255, 0), 1)

cv2.imshow("countours", image_with_contours)
cv2.waitKey(0)  
cv2.destroyAllWindows()

In [20]:
height,width = image_with_contours.shape[:2]
joined_contours_image = np.zeros((height, width), dtype=np.uint8)

area = []
for cnt in contours:
    curr_area = int(cv2.contourArea(cnt))
    area.append(curr_area)
    print(f"cnt :{cnt} -> area :{curr_area}")
    peri = cv2.arcLength(cnt, True)
    approx = cv2.approxPolyDP(cnt, 0.02 * peri, True)
    # Draw the approximated contour on the blank canvas
    cv2.drawContours(img, approx, -1, (0,0,255), 2)

cv2.imshow("Joined Approx Contours", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

cnt :[[[1279  681]]

 [[1278  682]]

 [[1277  682]]

 [[1276  683]]

 [[1275  683]]

 [[1274  684]]

 [[1273  684]]

 [[1272  684]]

 [[1271  684]]

 [[1270  685]]

 [[1269  685]]

 [[1268  686]]

 [[1267  686]]

 [[1266  686]]

 [[1265  687]]

 [[1264  688]]

 [[1263  688]]

 [[1262  688]]

 [[1261  689]]

 [[1260  689]]

 [[1259  689]]

 [[1258  690]]

 [[1257  691]]

 [[1256  691]]

 [[1255  691]]

 [[1254  691]]

 [[1253  692]]

 [[1252  693]]

 [[1251  693]]

 [[1250  693]]

 [[1249  694]]

 [[1248  695]]

 [[1247  695]]

 [[1247  696]]

 [[1247  697]]

 [[1248  697]]

 [[1249  698]]

 [[1250  698]]

 [[1251  698]]

 [[1252  698]]

 [[1253  699]]

 [[1254  699]]

 [[1255  700]]

 [[1256  700]]

 [[1257  701]]

 [[1258  701]]

 [[1259  702]]

 [[1260  702]]

 [[1261  703]]

 [[1262  703]]

 [[1263  704]]

 [[1264  704]]

 [[1265  704]]

 [[1266  704]]

 [[1267  705]]

 [[1268  705]]

 [[1269  706]]

 [[1270  706]]

 [[1271  707]]

 [[1272  707]]

 [[1273  707]]

 [[1274  708]]

 [[

In [24]:
import cv2
import numpy as np

# Load the image
image = cv2.imread('img\Retail_Sales_Distribution_Network_Dashboard_With_Forecasting_3.jpg')
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# Apply GaussianBlur to reduce noise and improve edge detection
blurred = cv2.GaussianBlur(gray, (5, 5), 0)

# Apply edge detection
edges = cv2.Canny(blurred, 50, 150)

# Find contours in the edge-detected image
contours, _ = cv2.findContours(edges, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)

# Initialize an empty list to store rectangles
rectangles = []

# Loop through contours and filter for rectangles
for cnt in contours:
    # Approximate the contour
    peri = cv2.arcLength(cnt, True)
    approx = cv2.approxPolyDP(cnt, 0.02 * peri, True)

    # Check if the approximated contour has four points and is convex
    if len(approx) == 4 and cv2.isContourConvex(approx):
        # Calculate the area and ignore small areas
        area = cv2.contourArea(approx)
        if area > 1000:  # Adjust area threshold as needed
            rectangles.append(approx)
            # Draw the rectangle on the original image
            cv2.drawContours(image, [approx], -1, (0, 255, 0), 2)

# Display the result
cv2.imshow("Rectangles Detected", image)
cv2.waitKey(0)
cv2.destroyAllWindows()


<>:5: SyntaxWarning: invalid escape sequence '\R'
<>:5: SyntaxWarning: invalid escape sequence '\R'
C:\Users\Rushi.bagul\AppData\Local\Temp\ipykernel_20020\1291945236.py:5: SyntaxWarning: invalid escape sequence '\R'
  image = cv2.imread('img\Retail_Sales_Distribution_Network_Dashboard_With_Forecasting_3.jpg')
